[package]
name = "timed_set"
version = "0.1.0"
authors = ["Mnatsakanov Andrey <andrey@3ig.kiev.ua>"]
edition = "2021"

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
debug-assertions = false
debug = false
opt-level = 3
lto = true
